# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.
"""

hexstring = "50617373776F72642069732064656573"
a_string = bytes.fromhex(hexstring)
a_string = a_string.decode("ascii")
print(a_string)

hexstring = "50613773776F72462069372064656573" #change 3 position
a_string = bytes.fromhex(hexstring)
a_string = a_string.decode("ascii")
print(a_string)

hexstring = "4c61756e63682061206d697373696c652d" #siganture hex
a_string = bytes.fromhex(hexstring)
a_string = a_string.decode("ascii")
print(a_string)

hexstring = "4c61756e63682061206d697373696c652e" #siganture hex change 1
a_string = bytes.fromhex(hexstring)
a_string = a_string.decode("ascii")
print(a_string)